#!/bin/bash

# If the current commit is a tag, push it to the docker repository

TAG=$(git describe --exact-match --tags HEAD 2>/dev/null)
if [ -n "$TAG" ]; then
  echo "=> Creating and pushing tag ${TAG}"
  docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
  docker push $DOCKER_REPO:$TAG
fi
